
let clownfilter = ["http://pbs.twimg.com/media/D-cQSmnW4AAzDUB.jpg:large", "http://pbs.twimg.com/media/D-cQgF1XYAAljiV.jpg:large", "http://pbs.twimg.com/media/D-cOxvIUYAALjrR.jpg:large", "http://pbs.twimg.com/media/D-cS4sXUYAA5mRj.jpg:large", "http://pbs.twimg.com/media/D-bpW07XYAAl-kL.jpg:large", "http://pbs.twimg.com/media/D-biP4-XsAAaM3s.jpg:large", "http://pbs.twimg.com/media/D-cUzWYXsAAKd77.jpg:large", "http://pbs.twimg.com/tweet_video_thumb/D-buDN-X4AE-UED.jpg:large", "http://pbs.twimg.com/media/D-cVTUBU0AAidSc.jpg:large", "http://pbs.twimg.com/tweet_video_thumb/D-cVYHhU8AAkI_B.jpg:large", "http://pbs.twimg.com/media/D-cV7PbXsAAz7Vf.jpg:large", "http://pbs.twimg.com/media/D-Zm4yvW4AAs9KH.jpg:large", "http://pbs.twimg.com/media/D-cZOkEUIAMQFF3.jpg:large", "http://pbs.twimg.com/media/D-cZ8x7UEAAy50A.jpg:large", "http://pbs.twimg.com/media/D-cajUEVUAAdasD.jpg:large", "http://pbs.twimg.com/tweet_video_thumb/D-cdVn3XUAEPeQz.jpg:large", "http://pbs.twimg.com/tweet_video_thumb/D-cdocBW4AAxBNE.jpg:large","http://pbs.twimg.com/tweet_video_thumb/D-b0z38WsAAePIw.jpg:large","http://pbs.twimg.com/media/D-cQyK7X4AALOtv.jpg:large","http://pbs.twimg.com/media/D-cWkLqWkAAkU3k.jpg:large","http://pbs.twimg.com/media/D-ZRXeAW4Ac3X-x.jpg:large","http://pbs.twimg.com/media/D-ceUtpUEAEHIK-.png:large","http://pbs.twimg.com/media/D-cfrwjUYAIv0v1.jpg:large","http://pbs.twimg.com/media/D-AsVFBWsAAXjT1.jpg:large","http://pbs.twimg.com/media/D-ajM3zXUAAa7it.jpg:large","http://pbs.twimg.com/media/D-cpYFOU0AA3kCe.jpg:large","http://pbs.twimg.com/media/D-cymJWXUAAVIPd.jpg:large","http://pbs.twimg.com/media/D-c5ae4VUAEZLQF.jpg:large","http://pbs.twimg.com/media/D-cPeQgXUAAgvhg.jpg:large","http://pbs.twimg.com/media/D-iNSchUYAoEQ12.jpg:large","http://pbs.twimg.com/media/D_Etw5hW4AELUff.jpg:large","http://pbs.twimg.com/media/D_EsXSRUEAACIXG.jpg:large"];

let pornfilter = ["http://pbs.twimg.com/media/D-chLHZUYAARUGP.jpg:large","http://pbs.twimg.com/ext_tw_video_thumb/1145909414001434624/pu/img/QG7rD968GRxEBQrj.jpg:large","http://pbs.twimg.com/ext_tw_video_thumb/1141105252176924672/pu/img/ZWx7-WCZT8dWbT0r.jpg:large","http://pbs.twimg.com/media/D8tiae1UEAAO3Qu.jpg:large","http://pbs.twimg.com/media/DfgoF8DWAAI5rJk.jpg:large","http://pbs.twimg.com/media/D8UM3VyU8AAUSFg.jpg:large","http://pbs.twimg.com/media/D7geRBLXYAEbuBf.jpg:large","http://pbs.twimg.com/media/D-kKDoaVUAA-FAl.jpg:large","http://pbs.twimg.com/ext_tw_video_thumb/748951771393953793/pu/img/Sh_9_3O_AaFCTqEh.jpg:large","http://pbs.twimg.com/ext_tw_video_thumb/1115554310195154944/pu/img/jyaDz43vqvwSJHwC.jpg:large","http://pbs.twimg.com/media/D5MdLXoW4AAAOeZ.jpg:large"];

let bigotry = ["http://pbs.twimg.com/media/D-UXVf5XkAEwEUO.jpg:large"];


let version = 0.04;
console.log(`filter v${version}`);
timeelm.innerHTML = `filter v${version}`;